imports:
    - { resource: ../../../../src/TargetAdds/Shared/Infrastructure/Symfony/DependencyInjection/target_adds.yaml }
services:
    _defaults:
        autoconfigure: true
        autowire: true

    Acme\Apps\TargetAdds\Front\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

        # Wire
    Acme\Shared\:
        resource: '../../../../src/Shared'

    Acme\TargetAdds\:
        resource: '../../../../src/TargetAdds'

    # -- APP DEFINITIONS --
    # Command/Query Handlers
    # Acme\Shared\Infrastructure\Bus\Command\InMemorySymfonyCommandBus:
    #   arguments: [!tagged acme.command_handler]
    #
    # Acme\Shared\Infrastructure\Bus\Query\InMemorySymfonyQueryBus:
    #   arguments: [!tagged acme.query_handler]
    #
    # RabbitMQ
    # CodelyTv\Shared\Infrastructure\Bus\Event\RabbitMq\RabbitMqConnection:
    #     arguments:
    #         - host: '%env(RABBITMQ_HOST)%'
    #     port: '%env(RABBITMQ_PORT)%'
    #     vhost: '%env(RABBITMQ_MOOC_VHOST)%'
    #     login: '%env(RABBITMQ_LOGIN)%'
    #     password: '%env(RABBITMQ_PASSWORD)%'
    #     read_timeout: 2
    #     write_timeout: 2
    #     connect_timeout: 5

    # Acme\Shared\Infrastructure\Bus\Event\RabbitMq\RabbitMqEventBus:
    #   arguments: ['@Acme\Shared\Infrastructure\Bus\Event\RabbitMq\RabbitMqConnection', '%env(RABBITMQ_EXCHANGE)%']

              # -- IMPLEMENTATIONS SELECTOR --
          # Acme\Shared\Domain\Bus\Event\EventBus: '@acme\Shared\Infrastructure\Bus\Event\WithMonitoring\WithPrometheusMonitoringEventBus'
          # Acme\Backoffice\Courses\Domain\BackofficeCourseRepository: '@acme\Backoffice\Courses\Infrastructure\Persistence\ElasticsearchBackofficeCourseRepository'
