imports:
    - { resource: ../../../../src/TargetAdds/Shared/Infrastructure/Symfony/DependencyInjection/target_adds.yaml }
services:
    _defaults:
        autoconfigure: true
        autowire: true

    exception.listener:
      class: Acme\Apps\TargetAdds\Front\EventListener\ExceptionListener
      tags:
        - { name: kernel.event_listener, event: kernel.exception }

    # Configure
    _instanceof:
        Acme\Shared\Domain\Bus\Event\DomainEventSubscriber:
            tags: ['acme.domain_event_subscriber']

    Acme\Shared\Domain\Bus\Command\CommandHandler:
        tags: ['acme.command_handler']

    Acme\Shared\Domain\Bus\Query\QueryHandler:
        tags: ['acme.query_handler']

    Acme\Apps\TargetAdds\Front\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    Acme\Apps\TargetAdds\Front\Command\:
        resource: '../src/Command'
        tags: ['console.command']

        # Wire
    Acme\Shared\:
        resource: '../../../../src/Shared'

    Acme\TargetAdds\:
        resource: '../../../../src/TargetAdds'

    # -- TAGGING --
    Acme\Shared\Infrastructure\Bus\Event\InMemory\InMemorySymfonyEventBus:
        arguments: [!tagged acme.domain_event_subscriber]
        lazy: true

    Acme\Shared\Infrastructure\Bus\Event\DomainEventMapping:
        arguments: [!tagged acme.domain_event_subscriber]

    Acme\Shared\Infrastructure\Bus\Event\DomainEventSubscriberLocator:
        arguments: [!tagged acme.domain_event_subscriber]

    Acme\Shared\Infrastructure\Doctrine\DatabaseConnections:
        arguments: [!tagged acme.database_connection]

    # -- IMPLEMENTATIONS SELECTOR
    Acme\Shared\Domain\Bus\Event\EventBus: '@Acme\Shared\Infrastructure\Bus\Event\MySql\DoctrineEventBus'
    Acme\TargetAdds\Tracking\Domain\CartRemovalRepository: '@Acme\TargetAdds\Tracking\Infrastructure\Persistence\MysqlCartRemovalRepository'
    Acme\TargetAdds\Tracking\Domain\DroppedItemRepository: '@Acme\TargetAdds\Tracking\Infrastructure\Persistence\MysqlDroppedItemsRepository'
