version: '3'

services:
  shared_rabbitmq:
    container_name: targetadds-rabbitmq
    image: 'rabbitmq:3.10.5-management'
    restart: unless-stopped
    ports:
      - "5630:5672"
      - "8090:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=targetadds
      - RABBITMQ_DEFAULT_PASS=target

  mooc_mysql:
    container_name: targetadds-mysql
    image: mariadb:10.7.4
    ports:
      - "3360:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    healthcheck:
      test: ["CMD", "mysqladmin", "--user=root", "--password=", "--host=127.0.0.1", "ping", "--silent"]
      interval: 2s
      timeout: 10s
      retries: 10
    command: ["--default-authentication-plugin=mysql_native_password"]

  # targetadds_backend_php:
  #   container_name: targetadds_backend_php
  #   user: "${UID}:${GID}"
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   restart: unless-stopped
  #   ports:
  #     - "8040:8040"
  #     - "9040:9001"
  #   volumes:
  #     - .:/app:delegated
  #   depends_on:
  #     - shared_rabbitmq
  #     - shared_prometheus
  #     - targetadds_elasticsearch
  #   command: symfony serve --dir=apps/targetadds/backend/public --port=8040

  targetadds_frontend_php:
    container_name: targetadds_frontend_php
    user: "${UID}:${GID}"
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8041:8041"
      - "9041:9001"
    volumes:
      - .:/app:delegated
    depends_on:
      - shared_rabbitmq
      - mooc_mysql
    command: symfony serve --dir=apps/targetadds/front/public --port=8041

