framework:
  secret: '%env(APP_SECRET)%'
  #csrf_protection: true
  #http_method_override: true
  http_cache: false

  # Enables session support. Note that the session will ONLY be started if you read or write from it.
  session:
    handler_id: null
    cookie_secure: auto
    cookie_samesite: lax
    enabled: true

  #esi: true
  #fragments: true
  php_errors:
    log: true
